<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Suyogs-MacBook-Pro.local" name="org.suyog.appium.yatra.tests.YatraAppTest" tests="1" failures="0" timestamp="4 Apr 2016 17:00:11 GMT" time="0.012" errors="1">
  <testcase name="SearchFlightFlow_VerifyFromToOnHeader" time="0.012" classname="org.suyog.appium.yatra.tests.YatraAppTest">
    <error type="java.lang.RuntimeException" message="Incorrect number of arguments provided...">
      <![CDATA[java.lang.RuntimeException: Incorrect number of arguments provided...
	at org.suyog.appium.yatra.pageobjects.AbstractPage.getElement(AbstractPage.java:60)
	at org.suyog.appium.yatra.pageobjects.LandingPage.gotoFlightSearchPage(LandingPage.java:15)
	at org.suyog.appium.yatra.tests.YatraAppTest.SearchFlightFlow_VerifyFromToOnHeader(YatraAppTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- SearchFlightFlow_VerifyFromToOnHeader -->
</testsuite> <!-- org.suyog.appium.yatra.tests.YatraAppTest -->
